src/InSillyClo/assemblies/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views, wizard_views

designer_wizard = wizard_views.AssemblyDesignerNotProtected.as_view(
    url_name='assemblies:designer-create-step',
)


app_name = 'assemblies'
urlpatterns = [
    path('', views.index, name='home'),
    path('about', views.about, name='about'),
    path('form-example', views.form_example, name='form_example'),
    path(
        'showcase',
        TemplateView.as_view(
            template_name="assemblies/showcase.html",
            extra_context=dict(
                theme_colors=[
                    "",
                    "simulator",
                    "designer",
                    "primary",
                    "secondary",
                    "success",
                    "info",
                    "warning",
                    "danger",
                    "light",
                    "dark",
                ],
                range6=list(range(1, 7)),
            ),
        ),
        name='showcase',
    ),
    path(
        'smp',
        TemplateView.as_view(
            template_name="assemblies/simple_message_page.html",
            extra_context=dict(
                page_title='page_title',
                message='message',
                sub_message='sub_message',
            ),
        ),
        name='simple-message-page',
    ),
    path('behind-the-tool', TemplateView.as_view(template_name="assemblies/behind-the-tool.html"), name='behind-tool'),
    path('team', TemplateView.as_view(template_name="assemblies/team.html"), name='team'),
    path('policy', TemplateView.as_view(template_name="assemblies/policy.html"), name='policy'),
    path('tutorial', TemplateView.as_view(template_name="assemblies/tutorial.html"), name='tutorial'),
    path('assembly-designer/create/<str:step>/', designer_wizard, name='designer-create-step'),
    path('assembly-designer/create/', designer_wizard, name='designer-create'),
    path('assembly/', views.AssemblyListView.as_view(), name='assembly-list'),
    path('assembly/<int:pk>/', views.AssemblyDetailView.as_view(), name='assembly-detail'),
    path('fragment', views.show_fragment, name='fragment'),
]

src/InSillyClo/insillyclo/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path("i18n/", include("django.conf.urls.i18n")),
    path('', include('django_kubernetes_probes.urls')),
    path('', include('basetheme_bootstrap.urls')),
    path('admin/', admin.site.urls),
    path('', include("assemblies.urls")),
    path('', TemplateView.as_view(template_name='base.html'), name='home'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/InSillyClo/assemblies/models.py
from django.contrib.auth import models as auth_models
from django.db import models
from django.db.models.functions import Upper
from django.utils.translation import gettext_lazy as _

from typing import List
import json


class UserManager(auth_models.UserManager):
    def create_user(self, email=None, password=None, **extra_fields):
        super().create_user(username=email, email=email, password=password, **extra_fields)

    def create_superuser(self, email=None, password=None, **extra_fields):
        super().create_superuser(username=email, email=email, password=password, **extra_fields)


class User(auth_models.AbstractUser):
    class Meta:
        ordering = [
            Upper("last_name"),
            Upper("first_name"),
        ]

    objects = UserManager()
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []
    email = models.EmailField(unique=True)


class Separator(models.TextChoices):
    COMMA = ',', _('Comma')
    HYPHEN = '-', _('Hyphen')
    UNDERSCORE = '_', _('Underscore')
    DOT = '.', _('Dot')
    TILDE = '~', _('Tilde')


class RestrictionEnzyme(models.Model):
    class Meta:
        verbose_name = _('Restriction Enzyme')
        verbose_name_plural = _('Restriction Enzymes')

    name = models.CharField(
        max_length=255,
    )
    site_for = models.CharField(
        max_length=50,
        null=True,
    )
    site_rev = models.CharField(
        max_length=50,
        null=True,
    )
    inter_s = models.PositiveIntegerField(
        default=0,
    )

    def __str__(self):
        return self.name


class InputPart(models.Model):
    class Meta:
        verbose_name = _('Input Part')
        verbose_name_plural = _('Input Parts')
        unique_together = (('assembly', 'order'),)
        ordering = ('assembly', 'order')

    suffix_type_letters = 'abcdefghijkl'
    name = models.CharField(
        max_length=255,
    )
    assembly = models.ForeignKey(
        "assemblies.Assembly",
        on_delete=models.CASCADE,
        related_name='input_parts',
    )
    order = models.PositiveSmallIntegerField(
        default=1,
        null=False,
        blank=False,
    )
    is_in_output_plasmid_name = models.BooleanField()
    is_mandatory = models.BooleanField()
    number_of_subparts_str = models.CharField(
        null=True,
        blank=True,
        default=None,
        max_length=64,
    )
    subpart_separator = models.CharField(
        max_length=1,
        choices=Separator.choices,
        default=None,
        null=True,
    )
    __number_of_subparts = None
    created_at = models.DateTimeField(
        auto_now_add=True,
    )
    updated_at = models.DateTimeField(
        auto_now=True,
    )

    @property
    def is_separable(self) -> bool:
        return self.number_of_subparts_str is not None and self.number_of_subparts_str is not ""

    @property
    def number_of_subparts(self) -> List[int]:
        if self.number_of_subparts_str is None or self.number_of_subparts_str == '':
            return list()

        if self.__number_of_subparts is None:
            self.__number_of_subparts = json.loads(self.number_of_subparts_str)

        return self.__number_of_subparts

    @property
    def allowed_subparts(self) -> str:
        for cpt in self.number_of_subparts:
            if cpt == 1:
                yield str(self.order)
                continue
            yield [f'{str(self.order)}{l}' for l in self.suffix_type_letters[:cpt]]

    def __str__(self):
        return self.name


class Assembly(models.Model):
    class Meta:
        ordering = [
            Upper("name"),
        ]
        verbose_name = _('Assembly')
        verbose_name_plural = _('Assemblies')

    name = models.CharField(
        max_length=255,
    )
    is_public = models.BooleanField(
        default=False,
    )
    owner = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='assemblies',
    )
    output_separator = models.CharField(
        max_length=1,
        choices=Separator.choices,
        default=Separator.DOT,
    )
    is_output_typed = models.BooleanField(
        default=False,
    )
    restriction_enzyme = models.ForeignKey(
        RestrictionEnzyme,
        on_delete=models.PROTECT,
    )
    is_input_part_typed = models.BooleanField()
    created_at = models.DateTimeField(
        auto_now_add=True,
    )
    updated_at = models.DateTimeField(
        auto_now=True,
    )

    def get_is_output_typed_display(self):
        if self.is_output_typed:
            return _('is_output_typed display when true')
        return _('is_output_typed display when false')

    def __str__(self):
        return self.name

src/InSillyClo/assemblies/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms import layout
from django.forms import formset_factory
from django.utils.translation import gettext as _

from assemblies.models import Assembly, InputPart

SEP_CHOICES = (
    (".", "Dot"),
    ("-", "dash"),
    ("~", "tilde"),
)


class AssemblyForm(forms.ModelForm):
    class Meta:
        model = Assembly
        fields = (
            'owner',
            'name',
            'is_output_typed',
            'output_separator',
            'restriction_enzyme',
            'is_input_part_typed',
        )
        widgets = {
            'owner': forms.HiddenInput(),
        }

    def __init__(self, owner, *args, **kwargs):
        self.owner = owner
        super().__init__(*args, **kwargs)

    def clean(self):
        cleaned_data = super().clean()
        cleaned_data['owner'] = self.owner
        return cleaned_data


class InputPartForm(forms.ModelForm):
    class Meta:
        model = InputPart
        fields = (
            'name',
            'is_in_output_plasmid_name',
            'is_mandatory',
            'number_of_subparts_str',
            'subpart_separator',
            'order',
        )
        widgets = {
            # 'order': forms.HiddenInput(),
            # 'number_of_subparts_str': forms.HiddenInput(),
        }

    helper = FormHelper()
    helper.form_tag = False
    helper.layout = layout.Layout(
        layout.Row(
            layout.Column(
                'order',
                'name',
                'is_in_output_plasmid_name',
                'is_mandatory',
                'number_of_subparts_str',
                'subpart_separator',
                layout.Div(
                    "DELETE",
                    css_class='d-none formset-delete-parent',
                ),
            )
        )
    )

    is_separable_in_sub_parts = forms.BooleanField(
        label=_("InputPartForm.is_separable_in_sub_parts.label"),
        help_text=_("InputPartForm.is_separable_in_sub_parts.help_text"),
        required=False,
    )

    def __init__(self, *args, **kwargs):
        # self.assembly = assembly
        super().__init__(*args, **kwargs)

    # def clean(self):
    #     cleaned_data = super().clean()
    #     cleaned_data['assembly'] = self.assembly
    #     return cleaned_data


InputPartFormFormSet = formset_factory(
    InputPartForm,
    can_delete=True,
    extra=0,
    min_num=1,
    validate_min=True,
)


class AssemblyFormDemo(forms.Form):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.layout = layout.Layout(
            layout.Fieldset(
                _('Name'),
                'name',
            ),
            layout.Fieldset(
                _('Naming convention for the Output Separator'),
                'separator',
                'separatorbis',
            ),
            layout.Fieldset(
                _('Type of the output plasmid'),
                'typed',
            ),
        )

    name = forms.CharField(
        label='',
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Name',
            }
        ),
    )
    separator = forms.ChoiceField(
        label='When computing the name of the output plasmid, what separator would you '
        'like to use to separate your input part names ?',
        help_text=" example: with ' - ' as separator, assembling pTDH3, GFP, tADH1 and a "
        "backbone would give pTDH3-GFP-tADH1-backbone",
        choices=SEP_CHOICES,
        widget=forms.Select(),
    )
    separatorbis = forms.ChoiceField(
        label='anotherone in this section',
        help_text=" example: with ' - ' as separator, assembling pTDH3, GFP, tADH1 and a "
        "backbone would give pTDH3-GFP-tADH1-backbone",
        choices=SEP_CHOICES,
        widget=forms.Select(),
    )
    typed = forms.BooleanField(
        label='Define part type for the output plasmid',
        help_text="To support Modular Cloning, InSillyClo allows you to assign types to genetic "
        "parts. Most Modular Cloning kit include iterative assemblies where the output "
        "plasmids of the first assembly are the input of the second. In such case it is "
        "important to be able to assign a type to the output plasmids of the first "
        "assembly.",
        widget=forms.CheckboxInput(),
    )


class AgreeForm(forms.Form):
    agree = forms.BooleanField(
        initial=False,
        required=True,
        label="",
    )

    def __init__(self, agree_label=None, agree_help_text=None, *args, **kwargs):
        self.helper = FormHelper()
        self.helper.form_tag = False
        super().__init__(*args, **kwargs)
        if agree_label is None:
            del self.fields["agree"]
        else:
            self.fields["agree"].label = agree_label
            self.fields["agree"].help_text = agree_help_text

src/InSillyClo/assemblies/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView

from assemblies import forms, models, utils


# Create your views here.


def index(request):
    context = dict(
        body_theme="with-logo",
    )
    return render(
        request=request,
        template_name='assemblies/index.html',
        context=context,
    )


def about(request):
    context = dict(
        body_theme="with-logo",
        fake_auth=True,
    )
    return render(
        request=request,
        template_name='assemblies/index.html',
        context=context,
    )


def show_fragment(request):
    context = dict(fragment=utils.get_fragments("pYTK002"))
    return render(request=request, template_name='assemblies/show_fragment.html', context=context)


def form_example(request):
    context = dict(
        title="ASSEMBLY DESIGNER (Fake form)", form=forms.AssemblyFormDemo(), form_title="ASSEMBLY Properties"
    )
    return render(
        request=request,
        template_name='assemblies/form_host.html',
        context=context,
    )


class AssemblyListView(
    ListView,
):
    model = models.Assembly

    def get_queryset(self):
        qs = super().get_queryset()
        # qs = self.model.annotate_is_empty(qs)
        # qs = qs.select_related('reviewer', 'candidate', 'stage')
        qs = qs.prefetch_related('input_parts', 'restriction_enzyme')
        return qs


class AssemblyDetailView(
    DetailView,
):
    model = models.Assembly

    def get_queryset(self):
        qs = super().get_queryset()
        qs = qs.prefetch_related('input_parts', 'restriction_enzyme')
        return qs

src/InSillyClo/assemblies/templates/assemblies/assembly_card.html
{% load assemblies_tags %}
{% load i18n %}

<div class="card">
    <div class="card-body row">
        <div class="col-12 col-xl-2 col-lg-3 col-md-3 me-md-4">
            <div class="fw-bolder">
                {{object.name|title}}
            </div>
            <small class="text-secondary">
                {{object|field_verbose_name:'updated_at'}}{%trans ':'%}<br/>
                {{object.updated_at}}
            </small>
        </div>
        <div class="col border-10 border-start border-primary ps-md-4">
            <div class="d-block">
                <span class="fw-bolder">
                    {{object|field_verbose_name_and_help_text:'output_separator'}}
                    {%trans ':'%}
                </span>
                {{object.get_output_separator_display}}
            </div>

            <div class="d-block">
                <span class="fw-bolder">
                    {{object|field_verbose_name_and_help_text:'restriction_enzyme'}}
                    {%trans ':'%}
                </span>
                {{object.restriction_enzyme.name}}
            </div>
            <div class="d-block mt-1">
                {%for ip in object.input_parts.all %}
                <span class="px-3 py-1 border border-{{ip.is_mandatory|yesno:'3,1'}} rounded-5 border-designer">{{ip}}</span>
                {%endfor%}
            </div>
            {% if show_see_more != False %}
            <div class="d-block mt-1 text-end">
                <a href="{%url 'assemblies:assembly-detail' object.pk %}">
                    {% trans "See more"%}
                </a>
            </div>
            {%endif%}
        </div>
    </div>
</div>

src/InSillyClo/assemblies/templates/assemblies/assembly_detail_content.html
{% load assemblies_tags %}
{% load i18n %}
<div class="card context-primary">
    <div class="card-body row">
        <div class="col-12">
            <h3>{%trans 'Assembly properties'%}</h3>
            <dl class="row">
                <dt class="col-3">
                    {{object|field_verbose_name_and_help_text:'name'}}
                    {%trans ':'%}
                </dt>
                <dd class="col-9">
                    {{object.name}}
                </dd>
                <dt class="col-3 text-secondary">
                    {{object|field_verbose_name_and_help_text:'created_at'}}
                    {%trans ':'%}
                </dt>
                <dd class="col-9 text-secondary">
                    {{object.created_at}}
                </dd>
                <dt class="col-3 text-secondary">
                    {{object|field_verbose_name_and_help_text:'updated_at'}}
                    {%trans ':'%}
                </dt>
                <dd class="col-9 text-secondary">
                    {{object.updated_at}}
                </dd>
                <dt class="col-3">
                    {{object|field_verbose_name_and_help_text:'output_separator'}}
                    {%trans ':'%}
                </dt>
                <dd class="col-9">
                    {{object.get_output_separator_display}}
                </dd>
                <dt class="col-11">
                    {{object.get_is_output_typed_display}}
                </dt>
                <dd class="col-1">&nbsp;</dd>
                <dt class="col-3">
                    {{object|field_verbose_name_and_help_text:'restriction_enzyme'}}
                    {%trans ':'%}
                </dt>
                <dd class="col-9">
                    {{object.restriction_enzyme.name}}
                </dd>
            </dl>
            <h3>{%trans 'Input parts'%}</h3>
        </div>
        {%for ip in object.input_parts.all %}
        <div class="col-12">
            {% include 'assemblies/input_part_card.html' with object=ip%}
        </div>
        {%endfor%}
    </div>
</div>

src/InSillyClo/assemblies/templates/assemblies/assembly_list.html
{% extends "assemblies/base.html" %}
{% load crispy_forms_tags %}
{% load i18n %}
{% load djangoscss %}
{% load assemblies_tags %}
{% load include_markdown %}

{% block title %}{{object_list|class_verbose_name_plural}}{% endblock %}
{% block page_title %}{{object_list|class_verbose_name_plural}}{% endblock %}

{%block content %}
{% for object in object_list %}
    <div class="col-12 mb-4">
        {% include 'assemblies/assembly_card.html' with object=object%}
    </div>
{%endfor%}
{%endblock content %}

src/InSillyClo/assemblies/templates/assemblies/commit_link.envsubst.html
<li class="nav-item">
<a class="nav-link mt-4 text-end text-secondary"
   href="$CI_PROJECT_URL/-/commit/$CI_COMMIT_SHA"
   >
    <i class="bi bi-git"></i> $CI_COMMIT_SHORT_SHA ($CI_COMMIT_REF_SLUG_SHORT)
</a>
</li>

src/InSillyClo/assemblies/templates/assemblies/commit_link.html
<li class="nav-item">
<a class="nav-link mt-4 text-end text-secondary"
   href="https://gitlab.pasteur.fr/hub/insillyclo/-/commits/main"
   >
    <i class="bi bi-git"></i> local
</a>
</li>

src/InSillyClo/assemblies/templates/assemblies/form_host.html
{% extends "assemblies/base.html" %}
{% load crispy_forms_tags %}
{% load i18n %}

{% block title %}{{ title }}{% endblock %}
{% block page_title %}{{ page_title|default:title }}{% endblock %}
{% block container_class %}container mb-4 context-designer{% endblock %}

{%block content_without_row%}
<form id='form'
      method="post"
      enctype='multipart/form-data'
      class="row"
>
    {% csrf_token %}
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                {{form_title}}
            </div>
            <div class="card-body">
                {%crispy form%}
            </div>
        </div>
    </div>
    <div class="col-12 text-center">
            <div class="mt-3 mb-1">
                <a href="?reset=True" class="text-dark">clear form</a>
            </div>
    </div>
    <div class="col-12 text-center">
            <div class="mb-3 mt-4">
                <input type="submit" name="submit" value="Submit" class="btn btn-auto">
            </div>
    </div>
</form>
{%endblock content_without_row%}

src/InSillyClo/assemblies/templates/assemblies/nav_bar.html
{% load djangoscss %}
{% load static %}
{% load i18n %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'assemblies:home'%}">{%trans "Home"%}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'assemblies:tutorial'%}">{%trans "Tutorial"%}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'assemblies:team'%}">{%trans "Team"%}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'assemblies:policy'%}">{%trans "Policy"%}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'assemblies:behind-tool'%}">{%trans "Behind the tool"%}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-success" href="{% url 'assemblies:assembly-list'%}">Asmb</a>
                </li>
<li class="nav-item dropdown lang">
    <a class="nav-link text-success" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown"
       aria-expanded="false">
        <i class="bi bi-wrench-adjustable-circle"></i>
    </a>
    <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
        <li class="nav-item">
            <a class="nav-link text-success" href="{% url 'assemblies:form_example'%}">{%trans "Form Example"%}</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-success" href="{% url 'assemblies:showcase'%}">Showcase</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-success" href="{% url 'assemblies:simple-message-page'%}">simple-message-page</a>
        </li>
<li class="nav-item">
    <a class="nav-link text-success"
       href="{% url 'admin:index'%}"
    >admin</a>
</li>
    </ul>
</li>

src/InSillyClo/assemblies/templates/assemblies/nav_bar_end.html
{% load djangoscss %}
{% load static %}
{% load i18n %}
<li class="nav-item dropdown lang">
    {% get_available_languages as available_languages %}
    {% get_current_language as LANGUAGE_CODE %}
    {% get_language_info_list for available_languages as langs %}
    <a class="nav-link " href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown"
       aria-expanded="false">
        <i class="bi bi-translate"></i>
    </a>
    <form action="{% url 'set_language' %}" method="post">
        {% csrf_token %}
        <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            {% get_language_info_list for available_languages as langs %}
            {% for lang in langs %}
            <li>
                <button class="dropdown-item {% if lang.code == LANGUAGE_CODE %}active{% endif %} text-capitalize"
                        type="submit"
                        name="language"
                        value="{{ lang.code }}"
                >
                    {{ lang.name_local }}
                </button>
            </li>
            {% endfor %}
        </ul>
    </form>
</li>
{%if request.user.is_authenticated%}
<li class="nav-item">
    <a class="btn btn-designer" href="{% url 'basetheme_bootstrap:account'%}"><i class="bi bi-person-circle"></i>{%trans "View profile"%}</a>
</li>
{%else%}
<li class="nav-item">
    <a class="btn btn-simulator" href="{% url 'basetheme_bootstrap:account'%}">{%trans "Login"%}</a>
</li>
{%endif%}

src/InSillyClo/assemblies/templates/assemblies/policy.html
{% extends "assemblies/base.html" %}
{% load crispy_forms_tags %}
{% load i18n %}
{% load djangoscss %}
{% load include_markdown %}

{% block title %}{%trans "Data privacy policy"%}{% endblock %}
{% block page_title %}{%trans "Data privacy policy"%}{% endblock %}

{%block content_without_row%}
<div class="card card-primary">
    <div class="card-body">
        {% include_md 'assemblies/md/%lg%/data-policy.md' %}
    </div>
</div>
{%endblock content_without_row%}

src/InSillyClo/assemblies/templates/assemblies/show_fragment.html
{% extends "assemblies/base.html" %}
{% load i18n %}
{% load djangoscss %}

{% block title %}InSillyClo{% endblock %}

{% block content_without_row %}

Outside sens: 
{{ fragment.0 }}

Inside sens: 
{{ fragment.1 }}

Inside antisens: 
{{ fragment.2 }}

Outside antisens: 
{{ fragment.3 }}

{% endblock %}

src/InSillyClo/assemblies/templates/assemblies/simple_message_page.html
{% extends "assemblies/base.html" %}
{% load i18n %}

{% block title %}{{title}}{% endblock %}
{% block page_title %}{{page_title}}{% endblock %}

{%block content_without_row%}
<div class="card card-{{ level|default:'primary'}}">
    <div class="card-body">
    <h5 class="d-none-empty">{% block message %}{{message}}{% endblock %}</h5>
    {% block sub_message %}{{sub_message}}{% endblock %}
    </div>
</div>
{%endblock content_without_row%}

src/InSillyClo/assemblies/templates/assemblies/tutorial.html
{% extends "assemblies/base.html" %}
{% load crispy_forms_tags %}
{% load i18n %}
{% load djangoscss %}
{% load include_markdown %}

{% block title %}{%trans "InSillyClo"%}{% endblock %}
{% block page_title %}{%trans "InSillyClo html case forced"%}{% endblock %}

{%block content_without_row%}
<h2>{%trans "Workflow details" %}</h2>
<div class="row mt-4">
    <div class="col-12">
        {%trans "At the core of InSillyClo lies the golden-gate assembly of input plasmids into an output plasmid."%}
    </div>
    <div class="col-12 col-xl-6 col-xxl-5 offset-xxl-1 mb-3 mt-3">
        <div class="card border-simulator">
            <div class="card-body text-center">
                <img class="h20em" src="{% sstatic '/img/golden-gate-assembly-1.svg' %}">
            </div>
        </div>
    </div>
    <div class="col-12 col-xl-6 col-xxl-5 mb-3 mt-3">
        <div class="card border-simulator">
            <div class="card-body text-center">
                <img class="h20em" src="{% sstatic '/img/golden-gate-assembly-2.svg' %}">
            </div>
        </div>
    </div>
    <div class="col-12">
        {% include_md 'assemblies/md/%lg%/workflow-details.md' %}
    </div>
    <div class="col-12 mt-5">
        <h2>{%trans "Tutorial" %}</h2>
    </div>
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                {% include_md 'assemblies/md/%lg%/setup-tutorial.md' %}
            </div>
        </div>
    </div>
    <div class="col-12 mt-5">
        <div class="card card-designer">
            <div class="card-body">
                {% include_md 'assemblies/md/%lg%/tutorial-designer.md' %}
            </div>
        </div>
    </div>
    <div class="col-12 mt-5">
        <div class="card card-simulator">
            <div class="card-body">
                {% include_md 'assemblies/md/%lg%/tutorial-simulator.md' %}
            </div>
        </div>
    </div>
</div>
{%endblock content_without_row%}